[book]
title = "Augsburg Rust Meetup"
#authors = ["Tiago Manczak", "Michael Schury"]
src = "src"
language = "en"

[output.html]
default-collapse = true

[output.html.playground]
editable = true

# Create PDF with toc
# [output.html]
# [output.pdf]
# [output.pdf-outline]
# PDF-File: ./book/pdf-outline/output.pdf
